[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --connect-under-reset --chip STM32F411RETx"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

#[profile.release]
#codegen-units = 1
#lto = true

[env]
DEFMT_LOG = "debug"
